TARGETS=\
  doc_sample.out \
  inject_exec.out \
  inject_make.out \
  inject_modified.out \
  inject_parse.out \
  unparse_exec.out \
  unparse_modified.out \

inject_exec.out: inject.py add_double.py
inject_make.out: inject.py call.py
inject_modified.out: inject.py add_double.py
inject_parse.out: inject.py call.py
unparse_exec.out: unparse.py double_and_print.py
unparse_modified.out: unparse.py double_and_print.py
