TARGETS=\
  func_obj.out \
  inherit_class.out \
  inherit_constructor.out \
  inherit_original.out \
  larger.out \
  shapes_class.out \
  shapes_dict.out \
  shapes_original.out \
  spread.out \
  varargs.out

include ../../examples.mk
