PYTHON_SRC = $(wildcard bin/*.py) $(wildcard src/*/*.py)

## ----------------------------------------

## check: check source code style
.PHONY: check
check:
	-flake8 ${PYTHON_SRC}
	-isort --check ${PYTHON_SRC}
	-black --check ${PYTHON_SRC}

# ----------------------------------------------------------------------

# These two PDFs are generated by hand, so don't try to convert SVG.
docs/doc-generator/fill-in-headers.pdf: src/doc-generator/fill-in-headers.pdf
	cp $< $@
docs/doc-generator/process-plain.pdf: src/doc-generator/process-plain.pdf
	cp $< $@
