TARGETS=\
  adder.out \
  closure.out \
  closure_list.out \
  dynamic.out \
  func.out \
  oop.out \
  map_closure.out \
  map_double.out \
  map_lambda.out

include ../../examples.mk

dynamic.out: dynamic.tll
func.out: func.tll
