TARGETS=\
  attribute.out \
  docstring.out \
  dry_run.out \
  find_list_test_funcs.out \
  find_report_tests.out \
  func_attr.out \
  func_dir.out \
  func_list.out \
  func_obj.out \
  import_example.out \
  replacement.out \
  show_locals.out \
  show_try_glob.out \
  try_glob.out \
  with_name.out

include ../../examples.mk
