TARGETS=\
  callable.out \
  find_test_funcs.out \
  func_list.out \
  globals.out \
  globals_plus.out \
  locals.out \
  manual.out \
  runner.out \
  signature.out \
  type_func.out \
  type_int.out \
  type_len.out

include ../../examples.mk
