TARGETS=\
  attribute.out \
  callable.out \
  docstring.out \
  find_test_funcs.out \
  func_attr.out \
  func_dir.out \
  func_list.out \
  func_obj.out \
  globals.out \
  globals_plus.out \
  manual.out \
  runner.out \
  signature.out \
  type_func.out \
  type_int.out \
  type_len.out \
  with_name.out

include ../../examples.mk
