TARGETS=\
  callable.out \
  docstring.out \
  dry_run.out \
  find_list_test_funcs.out \
  find_report_tests.out \
  func_attr.out \
  func_dir.out \
  func_list.out \
  func_obj.out \
  mock_object.out \
  replacement.out \
  show_locals.out

include ../examples.mk
