TARGETS=\
  tokenizer_collapse_error.out \
  tokenizer_collapse_example.out \
  tokenizer_test.out \
  test_parser.out \
  test_tokenizer.out

include ../examples.mk

tokenizer_collapse_example.py: tokenizer_collapse.py
tokenizer_test.out: tokenizer.py
