TARGETS=\
  parser_test.out \
  tokenizer_collapse_error.out \
  tokenizer_collapse_example.out \
  tokenizer_test.out

include ../examples.mk

parser_test.out: parser.py tokenizer.py
tokenizer_collapse_example.py: tokenizer_collapse.py
tokenizer_test.out: tokenizer.py
