TARGETS=\
  doubling.out \
  expr.out \
  repeat_zero.out \
  vars.out

include ../../examples.mk

doubling.out: doubling.tll vars.py
expr.out: expr.tll
repeat_zero.out: repeat_zero.tll
vars.out: vars.tll
