TARGETS=\
  exhaustive.out \
  incremental.out \
  incremental_reverse.out \
  manual.out \
  z3_complete.out \
  z3_equal.out \
  z3_part_equal.out \
  z3_triple.out \
  z3_unequal.out

include ../../examples.mk
