TARGETS=\
  callable.out \
  discovery.out \
  docstring.out \
  dry_run.out \
  mock_object.out \
  show_globals.out \
  show_tests.out

include ../../examples.mk

show_globals.out: show_globals.py
	python $< > $@
