TARGETS=\
  conditional.out \
  loop.out \
  multiple_variables.out \
  single_constant.out \
  single_variable.out \
  static_text.out \

include ../../examples.mk

EXTRAS = template.py vars.json

conditional.out: ${EXTRAS} conditional.ht
loop.out: ${EXTRAS} loop.ht
multiple_variables.out: ${EXTRAS} multiple_variables.ht
single_constant.out: ${EXTRAS} single_constant.ht
single_variable.out: ${EXTRAS} single_variable.ht
static_text.out: ${EXTRAS} static_text.ht
