TARGETS=\
  test_easy_mode.out \
  test_placed.out \
  test_parse_html.out \
  test_wrapped.out

include ../examples.mk

test_easy_mode.py: easy_mode.py
test_parse_html.py: parse_html.py
test_placed.py: placed.py
test_wrapped.py: wrapped.py
