TARGETS=\
  attribute.out \
  docstring.out \
  equilateral.out \
  func_attr.out \
  func_dir.out \
  inheritance_example.out \
  isosceles.out \
  scalene.out \
  with_name.out

include ../../examples.mk

inheritance_example.out: inheritance.py
