SRC=\
  env.py \
  expander.py \
  template.py \
  visitor.py \
  z_if.py \
  z_loop.py \
  z_num.py \
  z_var.py

TARGETS=\
  conditional.out \
  loop.out \
  multiple_variables.out \
  single_constant.out \
  single_variable.out \
  static_text.out \

include ../examples.mk
