TARGETS=\
  dump_ast.out \
  has_duplicate_keys_ast.out \
  walk_ast.out

include ../../examples.mk

dump_ast.out: simple.py
has_duplicate_keys_ast.out: has_duplicate_keys.py dump_ast.py
walk_ast.out: double.py
