TARGETS=\
  add_timestamps.out \
  check_cycles.out \
  expand_variables_no_vars.out \
  expand_variables_with_vars.out \
  graph_creator.out \
  pattern_attempt.out \
  pattern_final.out \
  update_timestamps.out

include ../../examples.mk
