TARGETS=\
  binary_notation.out \
  dynamic_format.out \
  hex_notation.out \
  pack_count.out \
  pack_unicode.out \
  pack_unpack.out \
  variable_packing.out \
  variable_unpacking.out

include ../../examples.mk

pack_unicode.py: variable_packing.py
variable_unpacking.py: variable_packing.py
